# Generated by Django 3.2.5 on 2021-11-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_history', '0001_initial'),
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('merchandise_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.merch')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile_history.user_profile_history')),
            ],
        ),
    ]
