# Generated by Django 3.2.6 on 2021-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_alter_merch_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merch',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
