# Generated by Django 3.2.5 on 2021-11-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_history', '0001_initial'),
        ('merchandise', '0002_merch_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch_rating',
            old_name='merchandise_sku',
            new_name='merchandise_id',
        ),
        migrations.AlterField(
            model_name='merch_rating',
            name='rated_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='profile_history.user_profile_history'),
        ),
    ]
