# Generated by Django 3.2.5 on 2021-11-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_history', '0001_initial'),
        ('merchandise', '0003_auto_20211119_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch_rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile_history.user_profile_history'),
        ),
    ]
