# Generated by Django 3.2.6 on 2021-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cost_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='class_type',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='instrument',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='instrument_level',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='lesson_minutes',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='lessons_per_week',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_frequency',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription_months',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
