# Generated by Django 3.2.6 on 2021-11-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_auto_20211028_1958'),
        ('invoice', '0002_auto_20211027_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='order_number',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='instrument_level',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lesson_minutes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lessons_per_week',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription_months',
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.merch')),
            ],
        ),
    ]
