# Generated by Django 3.2.5 on 2021-11-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20211103_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_cart',
            field=models.TextField(default=''),
        ),
    ]
