# Generated by Django 3.2.6 on 2021-11-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_history', '0001_initial'),
        ('invoice', '0004_invoice_original_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='profile_history.user_profile_history'),
        ),
    ]
