# Generated by Django 3.2.6 on 2021-09-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210907_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='friendly_name',
        ),
    ]
