# Generated by Django 3.2.6 on 2021-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210927_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='lesson_time_length',
            field=models.CharField(blank=True, choices=[('0.50', 'thirty minutes'), ('0.75', 'forty five minutes'), ('1.00', 'sixty minutes')], default='1.00', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lessons_per_week',
            field=models.CharField(choices=[('1', 'one lesson'), ('2', 'two lesson'), ('3', 'three lesson')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_duration_months',
            field=models.CharField(choices=[('.97', 'three months'), ('.94', 'six months'), ('.91', 'nine months'), ('.88', 'twelve months')], default='.88', max_length=4),
        ),
    ]
