# Generated by Django 3.2.6 on 2021-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20211004_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='lesson_time_length',
        ),
        migrations.AddField(
            model_name='subscription',
            name='lesson_minutes_length',
            field=models.CharField(choices=[('30', '30'), ('45', '45'), ('60', '60')], default='60', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lessons_per_week',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_duration_months',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('9', '9'), ('12', '12')], default='12', max_length=2),
        ),
    ]
