# Generated by Django 3.2.6 on 2021-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20211005_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(choices=[('30', '30'), ('45', '45'), ('60', '60')], default='60', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('private', 'private'), ('group', 'group'), ('prerecorded', 'prerecorded')], default='prerecorded', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_Per_Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_lessons', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(choices=[('3', '3'), ('6', '6'), ('9', '9'), ('12', '12')], default='3', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lesson_class_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lesson_minutes_length',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lessons_per_week',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_duration_months',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_class_type',
            field=models.ManyToManyField(to='lessons.Lesson_Style'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_minutes_length',
            field=models.ManyToManyField(to='lessons.Lesson_Minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessons_per_week',
            field=models.ManyToManyField(to='lessons.Lessons_Per_Week'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subscription_duration_months',
            field=models.ManyToManyField(to='lessons.Subscription_Months'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lesson_class_type',
            field=models.ManyToManyField(to='lessons.Lesson_Style'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lesson_minutes_length',
            field=models.ManyToManyField(to='lessons.Lesson_Minutes'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lessons_per_week',
            field=models.ManyToManyField(to='lessons.Lessons_Per_Week'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_duration_months',
            field=models.ManyToManyField(to='lessons.Subscription_Months'),
        ),
    ]
