# Generated by Django 3.2.6 on 2021-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20211006_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_class_type',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_minutes_length',
            new_name='lesson_minutes',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='subscription_duration_months',
            new_name='subscription_months',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='lesson_class_type',
            new_name='class_type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='instrument_included',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='level_included',
            new_name='instrument_level',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='lesson_minutes_length',
            new_name='lesson_minutes',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_duration_months',
            new_name='subscription_months',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
