# Generated by Django 3.2.6 on 2021-10-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20211007_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_months',
            name='months',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('9', '9'), ('12', '12')], default='3', max_length=2),
        ),
    ]
