# Generated by Django 3.2.6 on 2021-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_subscription_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='discount',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
