# Generated by Django 3.2.6 on 2021-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20211025_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
