# Generated by Django 3.2.6 on 2021-10-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20211027_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument_level',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
