# Generated by Django 3.2.6 on 2021-11-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20211027_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='instrument_level',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_minutes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lessons_per_week',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subscription_months',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='instrument_level',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lesson_minutes',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lessons_per_week',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_months',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Instrument_Level',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Lesson_Minutes',
        ),
        migrations.DeleteModel(
            name='Lesson_Style',
        ),
        migrations.DeleteModel(
            name='Lessons_Per_Week',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Subscription_Months',
        ),
    ]
